### ISSUE TITLE
Standard retrieval mode has preblems with reshaping

### ISSUE THREAD

**Issue by SergeyPetrakov** [HazyResearch/tabi#2]
(tabi) petrakov@nlp2:~/tabi$ python3 scripts/demo.py --model_checkpoint best_model.pth --entity_emb_path embs.npy --entity_file entity.pkl
2022-09-20 12:13:09,194 [INFO] Loading model...
2022-09-20 12:13:09,194 [INFO] Using encoder model: bert-base-uncased
Traceback (most recent call last):
  File "scripts/demo.py", line 67, in <module>
    model = Biencoder(
  File "/home/petrakov/tabi/tabi/models/biencoder.py", line 47, in __init__
    entity_embs = np.memmap(entity_emb_path, dtype="float32", mode="r").reshape(
ValueError: cannot reshape array of size 1950552064 into shape (768)

May be you can help me with it

**Comment by mleszczy** [comment]
Hi Sergey! Thanks for raising the issue! Which model checkpoint and embedding path are you using? Are these ones you trained or one of the four listed on the README?

**Comment by SergeyPetrakov** [comment]
Hi! I followed your instructions written in README. 
My step were the following (as stated in your README):
1) Made new conda environment with python=3.7
2) clone repo
3) `pip install -r requirements.txt`
4) `pip install -e . `
5) `pip install torch==1.10.1+cu111 torchvision==0.11.2+cu111 torchaudio==0.10.1 -f https://download.pytorch.org/whl/torch_stable.html`
6) download best_model.pth, embs.npy, entity.jsonl, entity.pkl
7) tried to launch TAbi interactively using `python scripts/demo.py --model_checkpoint best_model.pth --entity_emb_path embs.npy --entity_file entity.pkl`
After that I received above mentioned error

**Comment by mleszczy** [comment]
Hi Sergey, apologies for the slow reply. Can you check the md5 of the embedding file? These are the md5s for each of the embedding files (embs.npy): 
- KILT + types:  ace077de6422a8f827fd48dd7dbbd6cd
- KILT + no types:  88e787dc17e1807cdb93ecc310a94ea8
- BLINK + types: 07e56dac205931f9628de2d550a30a9e
- BLINK + no types:  dddd17917d23842a016a3490cbc87bed

If the md5 doesn't match one of the above, you may need to re-download the file. Please comment if that still doesn't work, thanks!

**Comment by SergeyPetrakov** [comment]
Hi Megan! No problem, thank you for md5 that you sent. I checked it, now it works as described in your repo. 
Btw, do I correctly understand that your model focuses only on input written in English? Can it be finetuned on the multilingual datasets to retrieve entities from other languages?
